-- Fix planned_workouts → calendar_events timezone handling
--
-- Problem:
--   sync_planned_workout_to_calendar() was building timestamptz values from (date + time)
--   without a timezone context. On Supabase (UTC), this caused scheduled workouts to appear
--   ~5 hours earlier in America/New_York (e.g., 9:00 AM ET showing as 4:00 AM).
--
-- Fix:
--   Interpret planned workout scheduled_date + scheduled_time as America/New_York local time,
--   then convert to timestamptz.

create or replace function sync_planned_workout_to_calendar()
returns trigger as $$
declare
  event_title text;
  event_start timestamptz;
  event_end timestamptz;
  duration_minutes int;
  workout_time time;
begin
  -- Generate title from day_label or workout_type
  event_title := coalesce(NEW.day_label, NEW.workout_type, 'Workout');

  -- Extract duration from prescribed JSON or default to 60 minutes
  duration_minutes := coalesce((NEW.prescribed->>'duration_min')::int, 60);

  -- Use scheduled_time if provided, otherwise default to 9 AM
  workout_time := coalesce(NEW.scheduled_time, '09:00'::time);

  -- Interpret (date + time) as America/New_York local time, then convert to timestamptz
  event_start := ((NEW.scheduled_date::date + workout_time)::timestamp at time zone 'America/New_York');
  event_end := event_start + (duration_minutes || ' minutes')::interval;

  insert into public.calendar_events (
    user_id,
    title,
    start_at,
    end_at,
    event_type,
    alignment_tag,
    notes,
    completed
  )
  values (
    NEW.user_id,
    event_title,
    event_start,
    event_end,
    'Workout',
    'planned_workout:' || NEW.id,
    NEW.notes,
    false
  )
  on conflict (user_id, alignment_tag)
  do update set
    title = excluded.title,
    start_at = excluded.start_at,
    end_at = excluded.end_at,
    notes = excluded.notes;

  return NEW;
end;
$$ language plpgsql security definer;

-- Resync existing planned workout calendar events to corrected times
-- Only touches rows generated by the planned_workout sync.
with pw as (
  select
    id,
    user_id,
    scheduled_date,
    coalesce(scheduled_time, '09:00'::time) as scheduled_time,
    coalesce(day_label, workout_type, 'Workout') as title,
    coalesce((prescribed->>'duration_min')::int, 60) as duration_minutes,
    notes
  from public.planned_workouts
), computed as (
  select
    pw.id,
    pw.user_id,
    pw.title,
    ((pw.scheduled_date::date + pw.scheduled_time)::timestamp at time zone 'America/New_York') as start_at,
    (((pw.scheduled_date::date + pw.scheduled_time)::timestamp at time zone 'America/New_York')
      + (pw.duration_minutes || ' minutes')::interval) as end_at,
    pw.notes
  from pw
)
update public.calendar_events ce
set
  title = c.title,
  start_at = c.start_at,
  end_at = c.end_at,
  notes = c.notes,
  event_type = 'Workout'
from computed c
where ce.user_id = c.user_id
  and ce.alignment_tag = 'planned_workout:' || c.id;
